name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Test ${{ matrix.os }}/${{ matrix.suite }}"
    strategy:
      fail-fast: false
      matrix:
        suite: [version-matrix, archival, misc]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: cachix/install-nix-action@v17
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: nix run '.#test-runner' -- $PWD "tests/${{ matrix.suite }}.bats"
